export const CART = 'CART'
export const CART_ADD_ITEM = `${CART}/ADD_ITEM`;
export const CART_UPDATE_ITEM = `${CART}/UPDATE_ITEM`;

export const CATALOGUE = 'CATALOGUE'
export const CATALOGUE_FETCH_PRODUCTS = `${CATALOGUE}/FETCH_PRODUCTS`

export const DATA_RESET_STATE = 'DATA/RESET_STATE';
export const DATA_RESET_SESSION = 'DATA/RESET_SESSION';